config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'inicio',to:'welcome#index',as:'inicio'
  get 'activities/shared',to:'activities#shared' ,as:"shared"
  resources :activities

  root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	has_attached_file :cover, styles:{ med:"1280x720", thump:"800x600" }
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities.all
    @activity = Activity.new
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    if user_signed_in?
      @activity = current_user.activities.new(activity_params)
      @activity.save
      redirect_to activities_path
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def shared
      @activities = Activity.all
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :description,:cover,:visible,:check1,:check2,:check3,:check4)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
  </div>
  <div class="field">
    
    <%= f.check_box :visible,id:"checkV" %>
    <%= f.label :visible,for:"checkV" %>
  </div>
  <div class="field">
    
    <%= f.check_box :check1,id:"check1" %>
    <%= f.label :check1,for:"check1" %>
  </div>
<div class="field">
    
    <%= f.check_box :check2,id:"check2" %>
    <%= f.label :check2,for:"check2" %>
  </div>
<div class="field">
    
    <%= f.check_box :check3,id:"check3" %>
    <%= f.label :check3,for:"check3" %>
  </div>
<div class="field">
    
    <%= f.check_box :check4,id:"check4" %>
    <%= f.label :check4,for:"check4" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="card-panel teal lighten-2 ">
  <h1 class="center-align">Emprendimientos</h1>
</div>
<div class=container>
  <div class ="row">
    <div class="col s12">
    <% @activities.each do |activity| %>
      <div class="col s12 m6 l6">
          <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%=image_tag(activity.cover.url)%>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= activity.title %><i class="material-icons right">more_vert</i></span>
          <div class="card-action">
              <%=link_to "Ver Emprendimiento", activity,class:"waves-effect waves-light btn"%>
              <%= link_to edit_activity_path(activity),class:"waves-effect waves-light btn" do %>
                <i class="material-icons left">cloud</i> Editar
              <%end%>
               <%= link_to activity, method: :delete,class:"waves-effect waves-light btn" do %>
                <i class="material-icons left">cloud</i> Eliminar
              <%end%>
          </div>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= activity.title %><i class="material-icons right">close</i></span>
          <p><%= activity.description %></p>
        </div>
      </div>  
        </div>
      <% end %>
</div>
  </div>
  </div>
<br>
<%if user_signed_in?%>
 <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <%= link_to "#modal1",class:"modal-trigger btn-floating btn-large waves-effect waves-light red" do%>
    <i class="material-icons">add</i>
  <%end%>
 </div>


  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Nuevo emprendimiento</h4>
      <%=render "form"%>
    </div>
  </div>

<%end%>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/shared.html.erb
<div class="card-panel teal lighten-2 ">
  <h1 class="center-align">Compartidos</h1>
</div>
<div class=container>
  <div class ="row">
    <div class="col s12">
    <% @activities.each do |activity| %>
      <div class="col s12 m6 l6">
          <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%=image_tag(activity.cover.url)%>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= activity.title %><i class="material-icons right">more_vert</i></span>
          <div class="card-action">
              <%=link_to "Ver Emprendimiento", activity,class:"waves-effect waves-light btn"%>
              <%= link_to edit_activity_path(activity),class:"waves-effect waves-light btn" do %>
                <i class="material-icons left">cloud</i> Editar
              <%end%>
               <%= link_to activity, method: :delete,class:"waves-effect waves-light btn" do %>
                <i class="material-icons left">cloud</i> Eliminar
              <%end%>
          </div>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= activity.title %><i class="material-icons right">close</i></span>
          <p><%= activity.description %></p>
        </div>
      </div>  
        </div>
      <% end %>
</div>
  </div>
  </div>
<br>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emprendimientos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <%=link_to "Emprendimientos",activities_path ,class:"brand-logo"%>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <%=render "partials/elementos"%>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <%=render "partials/elementos"%>
      </ul>
    </div>
  </nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
<script type="text/javascript">
  $(".button-collapse").sideNav();
    $(document).ready(function(){
      $('.parallax').parallax();
    });
    $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
        
</script>
</html>

app/views/partials/_elementos.html.erb
<li><%=link_to "Inicio",inicio_path%></li>
<li><%=link_to "compartidos",shared_path%></li>
<li><%=link_to "Mis emprendimientos", activities_path%></li>
<%if user_signed_in?%>
<li><%=link_to("#{current_user.email}",edit_user_registration_path)%></li>
<li><%=link_to("Salir",destroy_user_session_path, :method => :delete)%></li>
<%elsif%>
<li><%=link_to("Registrar",new_user_registration_path)%></li>
<li><%=link_to("Log in",new_user_session_path)%></li>
<%end%>

app/views/welcome/index.html.erb
<div class="section no-pad-bot" id="index-banner">
    <div class="parallax-container">
      <br><br>
      <div class="parallax"><%=image_tag("bg_1024.jpg")%></div>
      <h1 class="header center orange-text">Emprendiminetos</h1>
      <div class="row center">
        <%=link_to "Emprendimietos", activities_path, class:"btn-large waves-effect  teal lighten-2" %>
      </div>
      <br><br>

    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
    <br><br>

    <div class="section">

    </div>
  </div>
<div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
    <br><br>

    <div class="section">

    </div>
  </div>

  <footer class="page-footer orange">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>